### ISSUE TITLE
I think there are some problem which is provided by you

### ISSUE THREAD

**Issue by Gehrmanm** [msaadsaeed/SBNet#1]
I can't get train data

**Comment by Shahnawazgrewal** [comment]
The face and voice features used in our work can be accessed [here](https://drive.google.com/drive/folders/1O6VaVlV6k_WM-sXqFeAkXkX9iUddVNf7?usp=sharing). Once downloaded, place the files like this:

```
|-- data
  |-- voice
    |-- .csv files
  |-- face
    |--  .csv files
|-- imgs
|-- ssnet_cent_git
|-- ssnet_fop
|-- twobranch_cent_git
|-- twobranch_fop
```
